#!/bin/bash

# Install Java 17 (Amazon Corretto)
yum install java-17-amazon-corretto -y

# Download Tomcat 9.0.108
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.108/bin/apache-tomcat-9.0.108.tar.gz

# Extract Tomcat
tar -zxvf apache-tomcat-9.0.108.tar.gz

# Add manager-gui role to tomcat-users.xml
sed -i '56 a\<role rolename="manager-gui"/>' apache-tomcat-9.0.108/conf/tomcat-users.xml
sed -i '57 a\<user username="tomcat" password="admin@123" roles="manager-gui"/>' apache-tomcat-9.0.108/conf/tomcat-users.xml

# Allow access to manager GUI from all IPs
sed -i 's/<Valve.*RemoteAddr.*\/>//' apache-tomcat-9.0.108/webapps/manager/META-INF/context.xml

# Start Tomcat
./apache-tomcat-9.0.108/bin/startup.sh
